PUT http://localhost:8080/api/todo/1
Content-Type: application/json

{
  "id": 1,
  "description": "Завершить проект до понедельника"
}

###
PUT http://localhost:8080/api/todo
Content-Type: application/json

{
  "userId": 1,
  "description": "Завершить проект",
  "isCompleted": false
}
###

POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "Иван Иванов",
  "email": "ivan.ivanov@example.com",
  "isActive": true
}

###
PUT http://localhost:8080/api/user/1
Content-Type: application/json

{
    "id": 1,
    "name": "Иван Иванович",
    "email": "ivan.ivanovich@example.com",
    "isActive": false
}

